# Site settings
title: Legendevery
email: michaeldevery@gmail.com
url: https://github.com/legendevery/legendevery.github.io
description: "Building simple, reliable web applications"
keywords: "web development, backend development, application design, cork, php, symfony, website design"
skills: "Web Developer - Application Developer"
meta_author: Devery Michael

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Legendevery

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/michael_devery
  - title: stack-overflow
    url: https://stackoverflow.com/users/1196369/mickadoo
  - title: github
    url: http://github.com/mickadoo

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
